### ISSUE TITLE
Multiple mappings

### ISSUE THREAD

**Issue by OAPrilepa** [andrey-hohlov/ide-deploy-config#2]
http://joxi.ru/1bmoQd4IDao0Ay
http://joxi.ru/YxAelEqi936K2y

Текущая реализация плагина не учитывает это.
Было бы круто доделать.

Потребность есть, когда по sftp настраиваешь deployment в папку, которая содержит симлинки на папки другого уровня, который попадает в excluded или не попадает явно в параметры обмена.

Чтобы ничего не ломалось, приходится руками их прописывать.

**Comment by andrey-hohlov** [comment]
Added in 1.0.0
